### ISSUE TITLE
Analyze crash

### ISSUE THREAD

**Issue by Goetheus** [mcedit/mcedit2#278]
Hi everybody!

First of all, very good job on these beta version for McEdit, thank you :D

But, I noticed a crash yesterday on beta versions!

- MCEdit ver. beta 1 to beta 5.
- Minecraft ver. 1.10.2
- I use the 64-bit version of windows 10!

It's happen when we try to analyze a part of a world or all the world. With all my worlds (in different minecraft versions).

Here the error details:
```
MCEdit version: 2.0.0-beta5
Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.10586
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 365.19 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 660/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 837, in analyze (self is a EditorSession)
  File "mcedit2\util\showprogress.py", line 77, in showProgress  
  File "mceditlib\util\progress.py", line 26, in rescaleProgress  
  File "mceditlib\operations\__init__.py", line 36, in next (self is a AnalyzeOperation)
  File "mceditlib\operations\analyze.py", line 65, in operateOnChunk (self is a AnalyzeOperation)
TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'
```

Good luck! And thank you!

**Comment by codewarrior0** [comment]
Fixed!

**Comment by Goetheus** [comment]
Hi!

Sorry for the inconvenience but the problem is not fixed on the 2.0.0 beta 6 version!
I always get this error (with a little change at the end) : 

> MCEdit version: 2.0.0-beta6
> Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
> Platform: win32
> System version: Windows-10-10.0.14393
> Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
> 
> Obtained a GL context with this format:
> Valid: True
> Version: 4.5
> Hardware Accelerated: True
> Depth buffer: True, 24
> Double buffer: True
> Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile
> 
> Driver info:
> GL_VERSION: 4.5.0 NVIDIA 376.53 (4, 5)
> GL_VENDOR: 'NVIDIA Corporation'
> GL_RENDERER: 'GeForce GTX 660/PCIe/SSE2'
> 
> ------
> 
> Unhandled Exception
> 
> Traceback (most recent call last):
>   File "mcedit2\editorsession.py", line 837, in analyze (self is a EditorSession)
>   File "mcedit2\util\showprogress.py", line 77, in showProgress  
>   File "mceditlib\util\progress.py", line 26, in rescaleProgress  
>   File "mceditlib\operations\__init__.py", line 36, in next (self is a AnalyzeOperation)
>   File "mceditlib\operations\analyze.py", line 65, in operateOnChunk (self is a AnalyzeOperation)
> TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint64') with casting rule 'same_kind'

I can't analyze anything, and MCEdit is the only one which can do this :/

The line `self.blocks = numpy.zeros(65536, dtype='uintp')` is well replaced in your source code.
I need to add an "analyze.py" file in the plugins folder?!
